import '../globals.css'
import {Montserrat, Inter} from 'next/font/google'
import Header from "@/app/components/organisms/Header";
import {NextIntlClientProvider, useLocale} from 'next-intl';
import {notFound} from 'next/navigation';
import Footer from "@/app/components/organisms/Footer";

export function generateStaticParams() {
    return [{locale: 'en'}, {locale: 'de'}];
}

export const firaCode = Montserrat({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({children, params}) {
    const locale = useLocale();
    if (params.locale !== locale) {
        notFound();
    }

    let messages;
    try {
        messages = (await import(`../../content/${locale}.json`)).default;
    } catch (error) {
        notFound();
    }

    return (
        <html lang={locale}  >
        <body className={firaCode.className + " bg-[#EBECFF] bg-[url(/shapesbg.png)] bg-contain"} suppressHydrationWarning={true}>
        <NextIntlClientProvider locale={locale} messages={messages}>
            <Header className="containercustom"/>
            <div className="containercustom">
                {children}
            </div>
            <Footer/>
        </NextIntlClientProvider>
        </body>
        </html>
    )
}
